version = 0.1

[default.deploy.parameters]
stack_name = "auth-backend"
resolve_s3 = true
s3_prefix = "auth-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "FrontendUrl=\"https://fullstack-auth-platform-topaz.vercel.app\" BackendUrl=\"https://us6h43nkji.execute-api.ap-south-1.amazonaws.com/Prod\" SmtpHost=\"i2sj6ppudwtp.fips.wmjb.mail-manager-smtp.amazonaws.com\" SmtpPort=\"587\" MailFrom=\"Authlog <no-reply@thingsnxt.com>\" GoogleClientId=\"253492695515-vv6ko6cvi0d0otbb6f26ph0bg56l7qva.apps.googleusercontent.com\" GithubClientId=\"paste_your_github_client_id_here\""

[default.global.parameters]
region = "ap-south-1"
